### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by divyanshupathak** [t4t5/sweetalert#678]
Hello,
I simply install this package in my app (built in react) and it gives me following error -

```
W20170406-18:04:27.617(5.5)? (STDERR) /home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170406-18:04:27.617(5.5)? (STDERR) 						throw(ex);
W20170406-18:04:27.618(5.5)? (STDERR) 						^
W20170406-18:04:27.618(5.5)? (STDERR) 
W20170406-18:04:27.618(5.5)? (STDERR) ReferenceError: window is not defined
W20170406-18:04:27.618(5.5)? (STDERR)     at Object.logStr (/home/divyanshu/chatapp/node_modules/sweetalert/lib/modules/utils.js:37:7)
W20170406-18:04:27.619(5.5)? (STDERR)     at Object.<anonymous> (/home/divyanshu/chatapp/node_modules/sweetalert/lib/sweetalert.js:301:48)
W20170406-18:04:27.619(5.5)? (STDERR)     at Module._compile (module.js:409:26)
W20170406-18:04:27.620(5.5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170406-18:04:27.620(5.5)? (STDERR)     at Module.load (module.js:343:32)
W20170406-18:04:27.620(5.5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170406-18:04:27.620(5.5)? (STDERR)     at Module.require (module.js:353:17)
W20170406-18:04:27.620(5.5)? (STDERR)     at require (internal/module.js:12:17)
W20170406-18:04:27.620(5.5)? (STDERR)     at npmRequire (/home/divyanshu/chatapp/.meteor/local/build/programs/server/npm-require.js:133:10)
W20170406-18:04:27.621(5.5)? (STDERR)     at Module.Mp.useNode (packages/modules-runtime.js:493:20)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

Any clue/solution for this issue ?
Thanks.

**Comment by t4t5** [comment]
Sounds like your trying to run the library in a non-browser environment (Node.js?) which is why `window` is not defined. This library can only be used on the client side.

**Comment by divyanshupathak** [comment]
Actually I am using this library in meteor and I am new at Meteor. I have not any idea how to use it at client side. Your help is greatly appreciated.
Thanks

**Comment by t4t5** [comment]
https://forums.meteor.com/t/referenceerror-window-is-not-defined/27760

**Comment by divyanshupathak** [comment]
thanks @t4t5 , It works for me.
